"""Self-contained HTML report with severity filtering.

The report is a single file with inline CSS and a few lines of vanilla
JavaScript; it works offline and can be attached to pull requests or CI
artifacts.
"""

from __future__ import annotations

import html
from collections import Counter
from collections.abc import Sequence
from dataclasses import fields
from datetime import UTC, datetime

from repomind import __version__
from repomind.core.engine import AnalysisResult
from repomind.models.enums import Severity
from repomind.models.findings import Finding

_SEVERITY_COLORS: dict[Severity, str] = {
    Severity.CRITICAL: "#b91c1c",
    Severity.HIGH: "#c2410c",
    Severity.MEDIUM: "#a16207",
    Severity.LOW: "#1d4ed8",
    Severity.INFO: "#4b5563",
}

_GRADE_COLORS: dict[str, str] = {
    "A": "#15803d",
    "B": "#0e7490",
    "C": "#a16207",
    "D": "#c2410c",
    "F": "#b91c1c",
}

_STYLE = """
:root { color-scheme: light; }
* { box-sizing: border-box; }
body {
  margin: 0; padding: 2rem 1rem; line-height: 1.5; color: #0f172a; background: #f8fafc;
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
}
main { max-width: 1100px; margin: 0 auto; }
h1 { margin: 0; font-size: 1.6rem; }
h2 { margin: 2rem 0 0.75rem; font-size: 1.15rem; }
.meta { color: #64748b; margin: 0.25rem 0 1.5rem; }
.cards { display: flex; flex-wrap: wrap; gap: 1rem; align-items: center; }
.gauge {
  width: 130px; height: 130px; border-radius: 50%; display: grid; place-items: center;
  background: conic-gradient(var(--accent) calc(var(--score) * 1%), #e2e8f0 0);
}
.gauge-inner {
  width: 100px; height: 100px; border-radius: 50%; background: #fff; display: grid;
  place-items: center; text-align: center; font-weight: 700; font-size: 1.5rem;
}
.gauge-inner small { display: block; font-size: 0.7rem; font-weight: 400; color: #64748b; }
.stat {
  background: #fff; border: 1px solid #e2e8f0; border-radius: 10px;
  padding: 0.75rem 1rem; min-width: 150px;
}
.stat b { display: block; font-size: 1.25rem; }
.stat span { color: #64748b; font-size: 0.85rem; }
table {
  width: 100%; border-collapse: collapse; background: #fff;
  border: 1px solid #e2e8f0; border-radius: 10px; overflow: hidden;
}
th, td {
  text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #f1f5f9;
  vertical-align: top; font-size: 0.9rem;
}
th {
  background: #f1f5f9; font-size: 0.8rem; text-transform: uppercase;
  letter-spacing: 0.04em; color: #475569;
}
tr:last-child td { border-bottom: none; }
.badge {
  display: inline-block; padding: 0.1rem 0.5rem; border-radius: 999px;
  color: #fff; font-size: 0.72rem; font-weight: 600; text-transform: uppercase;
}
code { background: #f1f5f9; padding: 0.05rem 0.3rem; border-radius: 4px; font-size: 0.85em; }
.filters { margin: 0.75rem 0; display: flex; gap: 0.5rem; flex-wrap: wrap; }
.filters button {
  border: 1px solid #cbd5e1; background: #fff; border-radius: 999px;
  padding: 0.25rem 0.8rem; cursor: pointer; font-size: 0.85rem;
}
.filters button:hover { background: #f1f5f9; }
footer { margin-top: 2.5rem; color: #64748b; font-size: 0.85rem; }
"""

_SCRIPT = """
document.querySelectorAll("[data-filter]").forEach((button) => {
  button.addEventListener("click", () => {
    const filter = button.dataset.filter;
    document.querySelectorAll("#findings tbody tr").forEach((row) => {
      row.hidden = filter !== "all" && row.dataset.severity !== filter;
    });
  });
});
"""


def render_html(
    result: AnalysisResult,
    *,
    findings: Sequence[Finding] | None = None,
    top: int = 100,
) -> str:
    """Render the analysis result as a self-contained HTML document."""
    selected = list(result.findings if findings is None else findings)
    parts = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>RepoMind report - {_escape(result.root.name)}</title>",
        f"<style>{_STYLE}</style>",
        "</head>",
        "<body>",
        "<main>",
        *_header(result),
        *_summary(selected),
        *_findings(selected, top=top),
        *_suppressed(result),
        *_graph(result),
        *_history(result),
        *_thresholds(result),
        f"<footer>Generated by RepoMind v{__version__} - {_escape(str(result.root))}</footer>",
        "</main>",
        f"<script>{_SCRIPT}</script>",
        "</body>",
        "</html>",
    ]
    return "\n".join(parts) + "\n"


def _header(result: AnalysisResult) -> list[str]:
    """Render the title and the score gauge."""
    score = result.score
    accent = _GRADE_COLORS.get(score.grade, "#475569")
    scope = (
        f" - scope: changed since <code>{_escape(result.scope_label)}</code>"
        if result.scope_label is not None
        else ""
    )
    return [
        f"<h1>RepoMind report - {_escape(result.root.name)}</h1>",
        f'<p class="meta">{_escape(str(result.root))} - '
        f"{result.file_count} files, {result.total_loc:,} source lines - "
        f"{result.duration_seconds:.2f} s{scope}</p>",
        '<section class="cards">',
        f'<div class="gauge" style="--score: {score.value}; --accent: {accent}">'
        f'<div class="gauge-inner">{score.value}'
        f"<small>/100 - grade {score.grade}</small></div></div>",
        _stat(len(result.findings), "findings"),
        _stat(len(result.suppressed), "suppressed"),
        _stat(result.graph.module_count, "internal modules"),
        _stat(len(result.graph.cycles()), "import cycles"),
        "</section>",
    ]


def _stat(value: int, label: str) -> str:
    """Render one summary card."""
    return f'<div class="stat"><b>{value}</b><span>{label}</span></div>'


def _summary(findings: Sequence[Finding]) -> list[str]:
    """Render severity and category counts."""
    severity_counts = Counter(finding.severity for finding in findings)
    category_counts = Counter(finding.category for finding in findings)
    severity_cells = "".join(
        f'<span class="badge" style="background: {_SEVERITY_COLORS[severity]}">'
        f"{severity_counts.get(severity, 0)} {severity.label}</span> "
        for severity in reversed(list(Severity))
    )
    category_cells = "".join(
        f"<code>{_escape(category.value)}: {count}</code> "
        for category, count in sorted(category_counts.items(), key=lambda item: item[0].value)
    )
    return [
        "<h2>Summary</h2>",
        f"<p>{severity_cells}</p>",
        f"<p>{category_cells}</p>",
    ]


def _findings(findings: Sequence[Finding], *, top: int) -> list[str]:
    """Render the filterable findings table."""
    if not findings:
        return ["<h2>Findings</h2>", "<p>No findings above the configured thresholds.</p>"]

    buttons = "".join(
        f'<button data-filter="{severity.label}">{severity.label}</button>'
        for severity in reversed(list(Severity))
    )
    rows = []
    for finding in findings[:top]:
        color = _SEVERITY_COLORS[finding.severity]
        rows.append(
            f'<tr data-severity="{finding.severity.label}">'
            f'<td><span class="badge" style="background: {color}">'
            f"{finding.severity.label}</span></td>"
            f"<td><code>{_escape(finding.rule_id)}</code></td>"
            f"<td><code>{_escape(finding.location)}</code></td>"
            f"<td>{_escape(finding.message)}</td>"
            f"<td>{_escape(finding.suggestion or '')}</td>"
            "</tr>"
        )
    omitted = (
        f"<p><em>{len(findings) - top} more findings omitted.</em></p>"
        if len(findings) > top
        else ""
    )
    return [
        f"<h2>Findings ({len(findings)})</h2>",
        f'<div class="filters"><button data-filter="all">all</button>{buttons}</div>',
        '<table id="findings">',
        "<thead><tr><th>Severity</th><th>Rule</th><th>Location</th>"
        "<th>Message</th><th>Suggestion</th></tr></thead>",
        "<tbody>",
        *rows,
        "</tbody></table>",
        omitted,
    ]


def _suppressed(result: AnalysisResult) -> list[str]:
    """Render suppressed and baseline statistics."""
    if not result.suppressed and result.baseline_size is None:
        return []
    parts = ["<h2>Suppressed and accepted</h2>", "<ul>"]
    if result.suppressed:
        parts.append(f"<li>{len(result.suppressed)} finding(s) suppressed by configuration.</li>")
    if result.baseline_size is not None:
        known = len(result.findings) - len(result.new_findings)
        parts.append(
            f"<li>Baseline: {known} known, {len(result.new_findings)} new "
            f"({result.baseline_size} accepted entries).</li>"
        )
    parts.append("</ul>")
    return parts


def _graph(result: AnalysisResult) -> list[str]:
    """Render dependency graph statistics and cycles."""
    graph = result.graph
    parts = [
        "<h2>Dependency graph</h2>",
        f"<p><code>{graph.module_count}</code> modules, "
        f"<code>{graph.edge_count}</code> internal imports, "
        f"<code>{len(graph.cycles())}</code> cycles, "
        f"<code>{len(graph.external_imports)}</code> external packages.</p>",
    ]
    parts.extend(
        f"<p>cycle: <code>{_escape(' <-> '.join(cycle))}</code></p>" for cycle in graph.cycles()
    )
    return parts


def _history(result: AnalysisResult) -> list[str]:
    """Render Git churn hotspots."""
    history = result.history
    if history is None or not history.files:
        return []
    rows = "".join(
        "<tr>"
        f"<td><code>{_escape(entry.rel_path)}</code></td>"
        f"<td>{entry.commits}</td><td>{entry.churn}</td><td>{entry.author_count}</td>"
        f"<td>{entry.last_modified.strftime('%Y-%m-%d') if entry.last_modified else '-'}</td>"
        f"<td>{heat:.0f}</td>"
        "</tr>"
        for entry, heat in history.hotspots(limit=10)
    )
    return [
        f"<h2>Change hotspots (last {history.total_commits} commits)</h2>",
        "<table><thead><tr><th>File</th><th>Commits</th><th>Churn</th>"
        "<th>Authors</th><th>Last change</th><th>Heat</th></tr></thead>",
        f"<tbody>{rows}</tbody></table>",
    ]


def _thresholds(result: AnalysisResult) -> list[str]:
    """Render the thresholds used for this run."""
    rows = "".join(
        f"<tr><td><code>{_escape(field.name)}</code></td>"
        f"<td>{getattr(result.config.thresholds, field.name)}</td></tr>"
        for field in fields(result.config.thresholds)
    )
    return [
        "<h2>Thresholds used</h2>",
        f"<table><tbody>{rows}</tbody></table>",
        f'<p class="meta">Report generated {datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")}</p>',
    ]


def _escape(text: str) -> str:
    """Escape text for safe inclusion in HTML."""
    return html.escape(text, quote=True)
