"""Markdown report generation."""

from __future__ import annotations

from collections import Counter
from collections.abc import Iterable, Sequence
from dataclasses import fields
from datetime import UTC, datetime

from repomind import __version__
from repomind.core.engine import AnalysisResult
from repomind.models.enums import Category, Severity
from repomind.models.findings import Finding


def render_markdown(
    result: AnalysisResult,
    *,
    findings: Sequence[Finding] | None = None,
    top: int = 25,
) -> str:
    """Render the analysis result as a Markdown document.

    Args:
        result: The analysis result to render.
        findings: Optional pre-filtered findings; defaults to all findings.
        top: Maximum number of findings listed per category.

    Returns:
        The complete Markdown report.
    """
    selected = list(result.findings if findings is None else findings)
    lines: list[str] = []

    lines.extend(_header(result))
    lines.extend(_summary(result, selected))
    lines.extend(_new_findings_section(result))
    lines.extend(_findings_sections(selected, top=top))
    lines.extend(_suppressed_section(result))
    lines.extend(_dependency_section(result))
    lines.extend(_history_section(result))
    lines.extend(_warnings_section(result))
    lines.extend(_thresholds_section(result))

    return "\n".join(lines).rstrip() + "\n"


def _header(result: AnalysisResult) -> list[str]:
    """Render the document title and metadata."""
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    return [
        f"# RepoMind report - `{result.root.name}`",
        "",
        f"> Generated by RepoMind v{__version__} on {timestamp}  ",
        f"> Repository: `{result.root}`",
        "",
    ]


def _summary(result: AnalysisResult, findings: Sequence[Finding]) -> list[str]:
    """Render the executive summary tables."""
    score = result.score
    severity_counts = Counter(finding.severity for finding in findings)
    breakdown = " | ".join(
        f"**{severity_counts.get(severity, 0)}** {severity.label}"
        for severity in reversed(list(Severity))
    )
    return [
        "## Executive summary",
        "",
        *_table(
            ["Metric", "Value"],
            [
                ["Health score", f"{score.value}/100 (grade {score.grade})"],
                ["Findings", f"{len(findings)} ({breakdown})"],
                *(
                    [
                        [
                            "Baseline",
                            f"{len(result.findings) - len(result.new_findings)} known, "
                            f"{len(result.new_findings)} new",
                        ]
                    ]
                    if result.baseline_size is not None
                    else []
                ),
                *(
                    [["Scope", f"changed since `{result.scope_label}`"]]
                    if result.scope_label is not None
                    else []
                ),
                ["Suppressed", str(len(result.suppressed))],
                ["Python files", str(result.file_count)],
                ["Source lines", f"{result.total_loc:,}"],
                [
                    "Git history",
                    (
                        f"analyzed - last {result.history.total_commits} commits"
                        if result.history is not None
                        else "not analyzed"
                    ),
                ],
                ["Duration", f"{result.duration_seconds:.2f} s"],
            ],
        ),
        "",
    ]


def _findings_sections(findings: Sequence[Finding], *, top: int) -> list[str]:
    """Render one findings table per category."""
    if not findings:
        return ["## Findings", "", "No findings above the configured thresholds.", ""]

    lines: list[str] = ["## Findings", ""]
    by_category: dict[Category, list[Finding]] = {}
    for finding in findings:
        by_category.setdefault(finding.category, []).append(finding)

    for category in sorted(by_category, key=lambda item: item.value):
        category_findings = by_category[category]
        lines.append(f"### {category.value} ({len(category_findings)})")
        lines.append("")
        rows = [
            [
                finding.severity.label.upper(),
                f"`{finding.rule_id}`",
                f"`{finding.location}`",
                finding.message,
                finding.suggestion or "",
            ]
            for finding in category_findings[:top]
        ]
        lines.extend(_table(["Severity", "Rule", "Location", "Message", "Suggestion"], rows))
        if len(category_findings) > top:
            lines.append("")
            lines.append(f"_{len(category_findings) - top} more findings omitted._")
        lines.append("")
    return lines


def _new_findings_section(result: AnalysisResult) -> list[str]:
    """Render the findings that are not accepted by the baseline yet."""
    if result.baseline_size is None or not result.new_findings:
        return []
    rows = [
        [
            finding.severity.label.upper(),
            f"`{finding.rule_id}`",
            f"`{finding.location}`",
            finding.message,
        ]
        for finding in result.new_findings
    ]
    return [
        f"## New findings ({len(result.new_findings)})",
        "",
        *_table(["Severity", "Rule", "Location", "Message"], rows),
        "",
    ]


def _suppressed_section(result: AnalysisResult) -> list[str]:
    """Render the findings that configuration removed from the main report."""
    if not result.suppressed:
        return []
    rows = [
        [f"`{finding.rule_id}`", f"`{finding.location}`", finding.message]
        for finding in result.suppressed
    ]
    return [
        f"## Suppressed findings ({len(result.suppressed)})",
        "",
        *_table(["Rule", "Location", "Message"], rows),
        "",
    ]


def _dependency_section(result: AnalysisResult) -> list[str]:
    """Render dependency graph statistics, cycles and hubs."""
    graph = result.graph
    lines = [
        "## Dependency graph",
        "",
        *_table(
            ["Metric", "Value"],
            [
                ["Internal modules", str(graph.module_count)],
                ["Internal imports", str(graph.edge_count)],
                ["Import cycles", str(len(graph.cycles()))],
                ["External packages", str(len(graph.external_imports))],
            ],
        ),
        "",
    ]

    cycles = graph.cycles()
    if cycles:
        lines.append("### Import cycles")
        lines.append("")
        lines.extend(f"- {' <-> '.join(cycle)}" for cycle in cycles)
        lines.append("")

    hubs = graph.top_fan_in(limit=5)
    if hubs:
        lines.append("### Most imported modules")
        lines.append("")
        lines.extend(
            _table(["Module", "Imported by"], [[module, str(count)] for module, count in hubs])
        )
        lines.append("")

    call_hubs = result.call_graph.top_fan_in(limit=5)
    if call_hubs:
        lines.append("### Most called functions")
        lines.append("")
        lines.extend(
            _table(
                ["Function", "Callers"],
                [[symbol, str(count)] for symbol, count in call_hubs],
            )
        )
        lines.append("")

    lines.extend(_unstable_lines(result))

    return lines


def _unstable_lines(result: AnalysisResult) -> list[str]:
    """Render the instability table, or nothing when no module is coupled."""
    unstable = result.graph.top_unstable(limit=5)
    if not unstable:
        return []
    fan_in, fan_out = result.graph.fan_in(), result.graph.fan_out()
    return [
        "### Most unstable modules",
        "",
        *_table(
            ["Module", "Instability", "Ca", "Ce"],
            [
                [module, f"{value:.2f}", str(fan_in[module]), str(fan_out[module])]
                for module, value in unstable
            ],
        ),
        "",
    ]


def _history_section(result: AnalysisResult) -> list[str]:
    """Render Git churn hotspots."""
    history = result.history
    if history is None or not history.files:
        return []

    rows = []
    for entry, heat in history.hotspots(limit=10):
        last = entry.last_modified.strftime("%Y-%m-%d") if entry.last_modified else "-"
        rows.append(
            [
                f"`{entry.rel_path}`",
                str(entry.commits),
                str(entry.churn),
                str(entry.author_count),
                last,
                f"{heat:.0f}",
            ]
        )

    window = history.total_commits
    branch = history.branch or "detached HEAD"
    return [
        f"## Change hotspots (last {window} commits on {branch})",
        "",
        *_table(["File", "Commits", "Churn", "Authors", "Last change", "Heat"], rows),
        "",
    ]


def _warnings_section(result: AnalysisResult) -> list[str]:
    """Render engine warnings, if any."""
    if not result.warnings:
        return []
    lines = ["## Warnings", ""]
    lines.extend(f"- {warning}" for warning in result.warnings)
    lines.append("")
    return lines


def _thresholds_section(result: AnalysisResult) -> list[str]:
    """Render the thresholds used for this run."""
    rows = [
        [f"`{field.name}`", str(getattr(result.config.thresholds, field.name))]
        for field in fields(result.config.thresholds)
    ]
    return ["## Thresholds used", "", *_table(["Threshold", "Value"], rows), ""]


def _table(headers: Sequence[str], rows: Iterable[Sequence[str]]) -> list[str]:
    """Render a Markdown table."""
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    lines.extend("| " + " | ".join(_escape(cell) for cell in row) + " |" for row in rows)
    return lines


def _escape(cell: str) -> str:
    """Escape pipes and newlines so table cells stay well-formed."""
    return cell.replace("|", "\\|").replace("\n", " ")
